### ISSUE TITLE
Relation types for RepoDB?

### ISSUE THREAD

**Issue by tsafavi** [rahuln/lm-bio-kgc#1]
Hi, thanks for your contribution with this work! Quick question, does RepoDB have multiple relation types? I couldn't find anything about relations for RepoDB in the `data/processed/` directory, and the splits you provide suggest that there's only one type of relation between entities for this dataset. 

Tara

**Comment by rahuln** [comment]
Hi Tara, thanks for your question! That's correct, RepoDB only has one relation type ("<drug> _treats_ <disease>"), which is why it's missing a `*-relations.tsv` file in that directory.

**Comment by tsafavi** [comment]
thanks for the super fast response :)
