### ISSUE TITLE
CUDA error: out of memory when training kge model

### ISSUE THREAD

**Issue by giuliacassara** [rahuln/lm-bio-kgc#3]
Hi, I'm running this experiments: 

`python run.py --cuda --do_train --do_valid --do_test --dataset repodb --model DistMult --save_path ./results --subgraph /absolute-path-to/repodb-edge-split-f0.2-neg500-ind-s42.pt`

However I get a CUDA error: out of memory immediately 
`  File "run.py", line 276, in main
    kge_model = kge_model.cuda()`

Can I ask you what was your experimental setup in terms of GPU and memory?

**Comment by rahuln** [comment]
The experiments were run on various different GPUs with a minimum of 16 GB of GPU memory, although it may be possible to run them with less memory by adjusting hyperparameters (e.g., batch size). I'm able to run the command you listed above on a Tesla P100 GPU with 16 GB memory without getting a CUDA out-of-memory error. Hope that helps!

**Comment by giuliacassara** [comment]
Thank you, I solved by halving the batch size.
